# Generated by Django 5.1.6 on 2025-03-07 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id_autor', models.AutoField(db_column='T001IdAutor', editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='T001Nombre', max_length=100)),
                ('apellido', models.CharField(db_column='T001Apellido', max_length=100)),
                ('biografia', models.CharField(db_column='T001Biografia', max_length=20)),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'db_table': 'T001Autor',
            },
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id_editorial', models.AutoField(db_column='T002IdLibro', editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='T002Nombre', max_length=100)),
                ('direccion', models.TextField(db_column='T002Direccion', max_length=100)),
                ('telefono', models.CharField(db_column='T002Telefono', max_length=10)),
            ],
            options={
                'verbose_name': 'Editorial',
                'verbose_name_plural': 'Editoriales',
                'db_table': 'T002Editorial',
            },
        ),
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('id_miembro', models.AutoField(db_column='T004IdMiembro', editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='T004Nombre', max_length=40)),
                ('apellido', models.TextField(db_column='T004Apellido', max_length=40)),
                ('email', models.EmailField(db_column='T004Email', max_length=254)),
                ('fecha_membresia', models.DateField(db_column='T004FechaMembresia')),
            ],
            options={
                'verbose_name': 'miembro',
                'verbose_name_plural': 'miembros',
                'db_table': 'T004Miembro',
            },
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='persona',
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id_libro', models.AutoField(db_column='T003IdLibro', editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(db_column='T003Titulo', max_length=100)),
                ('resumen', models.TextField(db_column='T003Resumen', max_length=300)),
                ('isbm', models.TextField(db_column='T003Isbn', max_length=100)),
                ('publicacion', models.DateField(db_column='T003Publicacion')),
                ('autor', models.ForeignKey(db_column='T003IdAutor', on_delete=django.db.models.deletion.CASCADE, related_name='libros', to='api_app.autor')),
                ('editorial', models.ForeignKey(db_column='T003IdEditorial', on_delete=django.db.models.deletion.CASCADE, related_name='libros', to='api_app.editorial')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
                'db_table': 'T003Libro',
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id_prestamo', models.AutoField(db_column='T005Prestamo', editable=False, primary_key=True, serialize=False)),
                ('fecha_prestamo', models.DateField(db_column='T005FechaPrestamo')),
                ('fecha_devolucion', models.DateField(db_column='T005FechaDevolucion')),
                ('libro', models.ForeignKey(db_column='T005IdLibro', on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='api_app.libro')),
                ('miembro', models.ForeignKey(db_column='T005IdMiembro', on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='api_app.miembro')),
            ],
            options={
                'verbose_name': 'prestamo',
                'verbose_name_plural': 'prestamos',
                'db_table': 'T005Prestamo',
            },
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
        migrations.DeleteModel(
            name='Tarea',
        ),
    ]
