# Generated by Django 5.1.6 on 2025-03-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_autor_editorial_miembro_remove_tarea_persona_libro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='biografia',
            field=models.CharField(db_column='T001Biografia', max_length=500),
        ),
    ]
