# Generated by Django 5.1.6 on 2025-03-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0003_alter_autor_biografia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='biografia',
            field=models.CharField(blank=True, db_column='T001Biografia'),
        ),
        migrations.AlterField(
            model_name='editorial',
            name='telefono',
            field=models.CharField(blank=True, db_column='T002Telefono', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='libro',
            name='isbm',
            field=models.CharField(db_column='T003Isbn', max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='email',
            field=models.EmailField(db_column='T004Email', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='fecha_membresia',
            field=models.DateField(auto_now_add=True, db_column='T004FechaMembresia'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_devolucion',
            field=models.DateField(blank=True, db_column='T005FechaDevolucion', null=True),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_prestamo',
            field=models.DateField(auto_now_add=True, db_column='T005FechaPrestamo'),
        ),
    ]
