# Generated by Django 5.1.6 on 2025-03-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0004_alter_autor_biografia_alter_editorial_telefono_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='isbm',
            field=models.CharField(db_column='T003Isbn', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='libro',
            name='resumen',
            field=models.TextField(db_column='T003Resumen'),
        ),
    ]
